import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/router";
import Header from "../components/Header";

export default function Home() {
  const router = useRouter();
  console.log(router);
  return (
    <>
      <Head>
        <title>{`Resume Portfolio`}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <main className="about w-full md:flex md:justify-center  md:items-center md:h-screen py-10 px-2 md:px-0">
        <div className="about-wrapper xl:basis-7/12 basis-11/12 flex flex-col lg:flex-row">
          <figure className="md:basis-2/4 order-2">
            <Image
              src={`/images/profile.jpg`}
              alt="profile image"
              width="480"
              height="480"
              layout="responsive"
              className="w-full object-cover rounded-full grayscale hover:grayscale-0 cursor-pointer"
            />
          </figure>
          <section className="md:basis-2/4 flex lg:order-2  items-center md:pl-4 p-2 mb-10 ">
            <p className="flex flex-wrap">
              <span className="md:text-5xl text-4xl md:font-medium mb-4">
                Hello! I'm John Doe.
              </span>
              <span className="text-l font-normal">
                Web Developer From Tokyo, Japan. I am passionate about Web
                Designing. I have rich experience in Magento, also I'm good at
                WordPress. I love to talk with you about our unique.
              </span>
            </p>
          </section>
        </div>
      </main> */}
    </>
  );
}
